In [1]:
import csv
import pymysql

conn = pymysql.connect(host='localhost', user='root', password='123123', db='gidseller', charset='utf8')

curs=conn.cursor()
conn.commit()

f=open('file.csv','r' , encoding ='utf-8-sig')
csvReader=csv.reader(f)

for row in csvReader:
    print(int(row[0])+2)
    
    sql= """insert into g5_phone_list (pl_id, pl_maker, pl_group, pl_model_code, pl_name, pl_model_name, pl_storage, pl_color_name, pl_hidden, pl_storage_hidden, pl_color_hidden, pl_class_hidden, pl_color_code, pl_launch, pl_size, pl_display_inch, pl_display_cm, pl_weight, pl_battery, pl_front_camera, pl_back_camera, pl_external_storage, pl_review, pl_info_model, pl_info_series, pl_info_version, pl_info_subname_1, pl_info_subname_2, pl_info_aka, pl_review_1,pl_review_2,pl_review_3) 
    values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
    curs.execute(sql,(int(row[0]),row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9],row[10],row[11],row[12],row[13],row[14],row[15],row[16],row[17],row[18],row[19],row[20],row[21],row[22],row[23],row[24],row[25],row[26],row[27],row[28],row[29],row[30],row[31]))

3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270