In [10]:
import pandas as pd
import re
a = pd.read_csv("outputs/0409add-reveiw_all.csv")

#리뷰내용중에서 앞뒤 공백 전체제거하는 함수
def fix(df, col):
    for i in df.index:
        cont = str(df.loc[i, col])
        cont = cont.strip() 
        df.loc[i, col] = cont
        
        return df

#리뷰내용중에서 제품내용 포함되어있는지 valid 열 추가하는 함수
def fillter(df,col):
    df['valid'] = 'N'
    regex = re.compile(
        r'용량|색|사이즈|인치|화면|무게|센치|배터리|카메라|메모리|성능|출시|속도'
        + r'|[0-9]+기가|보급형|방수|무선충전|지문인식|스크린|디스플레이|스펙|내장'
        + r'|외장|컬러|버튼|단자|현상|듀얼|화소|내구성|발열|업데이트|C타입'
        )
    
    for i in df.index:
        cont = df.loc[i, col]
        if regex.search(cont): 
            df.loc[i,'valid'] = 'Y'
        else:
            pass
        df.loc[i, col] = cont
        return df

fix(a,'text')
fillter(a,'text')

In [ ]:
a.rename(columns = {'upload_day' : 'upload_date', 'text' : 'content'}, inplace = True)
del a['Target']
a.head(1)

In [24]:
a

,pl_id,pl_model_code,pl_name,star,market,write_id,upload_date,title,content,URL,valid
0,210.0,SM-G988,갤럭시 S20 울트라,NaN,11번가,blu*******,2020-11-15,NaN,새제품급은 무슨...헐 \r\n중고제품 중고라고 안써놓고 파는건 여전하네 \r\n새...,https://www.11st.co.kr/catalog/catalogDetail.t...,N
1,210.0,SM-G988,갤럭시 S20 울트라,5.0,11번가,538***,2020-10-27,NaN,걸럭시S20 울트라 988N을 사용해보니까 속도도 상당히 빠르고 S급을 받아보니까 ...,https://www.11st.co.kr/catalog/catalogDetail.t...,Y
2,210.0,SM-G988,갤럭시 S20 울트라,5.0,11번가,sjs*****,2020-04-20,NaN,가개통폰이라 가격싸게 잘산것같습니다. 원하는 통신사로 보내주셔서 딱좋았습니다. 아쉬...,https://www.11st.co.kr/catalog/catalogDetail.t...,N
3,210.0,SM-G988,갤럭시 S20 울트라,5.0,11번가,rhz****,2020-06-25,NaN,상품은 만족스럽습니다.. 다만 배송이 너무나도 느려요.. 이전 기기가 고장나서 주문...,https://www.11st.co.kr/catalog/catalogDetail.t...,N
4,210.0,SM-G988,갤럭시 S20 울트라,5.0,11번가,ljs*****,2020-12-22,NaN,빨리오네요 주문하고 3일정도 내로 도착했어요. \r\n풀박스 안와서문의했는데 바로 ...,https://www.11st.co.kr/catalog/catalogDetail.t...,N
...,...,...,...,...,...,...,...,...,...,...,...
618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,N
619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,N
620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,N
621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,N
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,N

In [23]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine

# MySQL Connector using pymysql
pymysql.install_as_MySQLdb()
import MySQLdb



engine = create_engine("mysql+mysqldb://root:"+"123123"+"@localhost/gidseller", encoding='utf-8')
conn = engine.connect()

a.to_sql(name='review_list', con=engine, if_exists='append', index=False)

In [30]:

connection = pymysql.connect(host='localhost', user='root', password='123123', db='gidseller')

try:
    with connection.cursor() as cursor:
        sql =( "INSERT INTO g5_phone_review (pr_model_code ,pr_model_name ,pr_star ,pr_market ,pr_write_id ,pr_upload_date ,pr_title ,pt_text ,pr_url )"
              "(SELECT pl_model_code, pl_name, star, market, write_id, upload_date, title, content, URL FROM review_list WHERE pl_model_code NOT IN (SELECT DISTINCT pr_model_code FROM g5_phone_review))" )

        cursor.execute(sql)

    connection.commit()

finally:
    connection.close()